### ISSUE TITLE
std::bad_function thrown when attempting to handle response at client

### ISSUE THREAD

**Issue by dgreatwood** [oktal/pistache#117]
I was seeing std::bad_function thrown in client.cc.

Catching it in the debugger, it was caused by onDone (callback address) being NULL. Seems to happen when the server side decides to close a connection (perhaps after a period of inactivity?).

On further investigation, the "response" (i.e. the close connection) is happening when inflightRequests is empty.

The current code is doing stuff like:
```C++
Connection::handleResponsePacket(const char* buffer, size_t bytes) {
        ...
        auto req = std::move(inflightRequests.front());
        inflightRequests.pop_back();

        ...

        req.resolve(std::move(parser_.response));
        req.onDone();
        ...
}
```

According to C++ documentation, "Calling front on an empty container is undefined" for std::deque (inflightRequests is a std::deque). What actually seems to happen is that front returns a default-constructed request - which has null onDone.

We could guard all such cases in client.cc by checking for empty inflightRequests and for null onDone, something like this:
```C++
Connection::handleResponsePacket(const char* buffer, size_t bytes) {
        ...
        if (!inflightRequests.empty())
        {
        auto req = std::move(inflightRequests.front());
        inflightRequests.pop_back();

        ...

        req.resolve(std::move(parser_.response));
        if (req.onDone)
                req.onDone();
        ...
        }
}
```
Doing this in the client.cc places where we're pulling from inflightRequests fixes the problem for me.

**Comment by kennymalac** [comment]
submit a pull request please ;)

**Comment by dgreatwood** [comment]
:-)
Done. branch: checkBeforeCallOnDone

**Comment by oktal** [comment]
Hello.

I'm not sure that checking for empty-ness of the `inflightRequests` queue is the right thing to do here.
It looks like there is an issue somewhere else.

Basically, we finished parsing a response (the parser return `Done`) but we do not have any inflight request in queue, which does not really make sense. Are you able to easily reproduce the issue on your side ? If yes, could you try to `tcpdump` and join the resulting pcap file to the issue so that we can try analyzing more deeply what's happening ?

**Comment by dgreatwood** [comment]
I could try with the tcpdump, but maybe a little more info will be enough.

The case I am seeing is Connection::handleError called with error: "Connection reset by peer"

The problem happens after several minutes of inactivity on the connection. Stack trace enclosed.

Is what's happening as simple as: Polling::Event is created due to other end choosing to terminate connection, event detected in runOnce, then passed down to Connection::handleError which crashes because it wrongly assumes there must be a inflight request in order for there to be an event on the connection?

Or LMK if you do need a tcpdump :-)

Thanks.

[st.txt](https://github.com/oktal/pistache/files/1185805/st.txt)

**Comment by oktal** [comment]
Oh I see. I initially thought the problem came from `handleResponsePacket`.

If it does happen during `handleError`, then it makes a little bit more sense and I think that checking for `inflightRequests` empty-ness might be the right thing to do there.

I'll investigate a little bit more but if I come to the same conclusion, I'll merge your PR in.

**Comment by dgreatwood** [comment]
Sounds good.

Btw checking may be a reasoanable precaution in the non-error cases too IMHO. Just as an example, imagine that a request times out at the exact moment a response is finally received from the server. Then you have a race between the process-response code and the process-timeout code; whichever looses the race is likely to be looking at empty inflightRequests isn't it, since the race winner will have stripped the request from the queue?

Granted I saw the issue in practice in the error case.

**Comment by xoac** [comment]
I think it can resolve also #104. If u marge place notify me I will test it.

**Comment by rushigerrard** [comment]
Any update on this issue?
