### ISSUE TITLE
Async::Promise::then(...) thread reference

### ISSUE THREAD

**Issue by ajallooeian** [oktal/pistache#23]
Does Async::Promise::then(...) return a reference to the created thread so it can be join()- or detach()- ed? Without joining, the program can return "terminate called without an active exception". 

A discussion here: 
http://stackoverflow.com/questions/7381757/c-terminate-called-without-an-active-exception

**Comment by oktal** [comment]
Hello,

`Async::Promise<T>` really does not have everything to do with threads. The primary goal of a `Promise` is to dissociate the launch of an asynchronous operation from the retrieval of its result. While you could launch an asynchronous operation in a separate thread, you could also perfectly imagine simply deferring it by posting a "signal" into your main thread event-loop so that it will be executed on the next event loop run.

That being said, a `Promise` does not return any thread handle, as it is not creating any thread.
