### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by Kiura** [oktal/pistache#3]
Hello, does this library implement websockets? and how mature this library? can it be used for production? Impressive library btw.

Also, I am writing my own project at the moment in `golang`, and I was thinking to rewrite to `c++` using this library and probably due these reasons: less dependencies, more performant? full control over memory, also wanted to learn more c++ (at least thats what i am thinking), and the question is "is it worth it?" ))

**Comment by oktal** [comment]
Hello,

websockets are currently not supported but that would definitely be something that I'd be interested in to implement or even accept any contribution in that sense.

> and how mature this library?

It's been here for a couple of months now and I've been trying to fix as many things as I can

> can it be used for production? 

Definitely. If you decide to do so, please let me know how it goes, I'd like to have user feedback on using it in production.

> Impressive library btw.

Thanks !

As for go, that's indeed a good choice for any networking-related application (they have everything you would need in their standard library, as well as a nice and built-in support for concurrency through their coroutines and channels).

As for the advantage of my solution vs go, I did not really benchmark mine over the go implementation, so I can not tell performance-wise, but you will benefit for lower level constructs and components (I'm currently working a refactoring my API so that you can access the event-loop and put your fds in there for any async code that you would need, like nginx does). If you want to try and learn more about C++, that should be a good fit for you, as I'm trying to keep my API clean, consistent, and easy to use.

In any case, let me know if you have any question about it.

**Comment by Kiura** [comment]
My project requires websockets. I am gonna wait until they are implemented so I can try the library out (and learn c++ from the ground). I would contribute to the project but I am gonna do more harm than good cos of luck of knowledge )) however, feel free to contact me if there is anything I can help with.

As for other issue... please dont try to make the library crossplatform cos its gonna take a lot of time to implement one functionality on all OSes. I would also suggest to concentrate on main features and performance (yep, I am performance freak ))

P.S. It could be a good idea to put TODO on readme page.
P.P.S. let me know if I can help or if you wanna discuss anything.

**Comment by jeffvandyke** [comment]
I think WebSockets would be a really nice addition as well. In our project we have some really good use-cases for them, and are getting by with polling for now. I might within a couple weeks take a look at the spec, the TCP/IP layer of this library, and see what might need to be done in order to get support working.  I've only been using C++ for work for a few months, so I could really use assistance in figuring out how to best implement certain parts.

The spec is located at <https://tools.ietf.org/html/rfc6455>, and I saw in a stack overflow answer someone basically recommending implementing websockets for a project; it's supposed to be a simple enough protocol. There's a page on <https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers> that gives low level information about the protocol.

**Comment by jeffvandyke** [comment]
Revisiting this topic, it seems as though integrating uWebSockets would be a better path forward, going off of an excellent existing implementation, though it's not well documented :(

**Comment by mohsenomidi** [comment]
Currently the Pistache does not support web socket. this issue can be closed. 

@dennisjenkins75  we could create the project task and add these type of requirements there, by plan or by any volunteer can be done.
