### ISSUE TITLE
Stream image as binary

### ISSUE THREAD

**Issue by rolandjitsu** [oktal/pistache#548]
Would it be possible to use the response stream to stream images to a client? I need to stream a camera feed from a raspberry pi to a phone and I was thinking of using websockets, but this lib does not have this feature baked in.

I see https://github.com/oktal/pistache/issues/204 is sort of similar, but I'm not fond of sending base64 strings over the network, especially when I have high res images.

**Comment by hydratim** [comment]
That should be possible, but I would expect it to be a little unstable.
You'll also need to be really careful with your buffers (easy to create memory leaks when attempting to do this).

Give it a try and let us know!

**Comment by rolandjitsu** [comment]
I understand. What would be a good alternative then? Use base64?

I cannot stream a video directly from the camera (which is what I would do) because it can only be used by one process and there is already a process using it, but the api is part of that process, so it can get access to the camera object to get frames.

**Comment by hydratim** [comment]
Typically for this class of problem you'd use a double (or triple) buffer: 

- https://gameprogrammingpatterns.com/double-buffer.html
- https://codereview.stackexchange.com/questions/163810/lock-free-zero-copy-triple-buffer
- https://en.wikipedia.org/wiki/Multiple_buffering

This would allow you to read a frame from the camera in one thread, toggle the buffer flip and read the next frame and then toggle again.
This decouples the camera reading from the data transmission, once you've done this you can have a slow running converter, compressor, and / or down-sampler that would adjust the image quality depending on the http request and connection quality.

What ever you use as your transmission format it's going to be relatively unreliable (HTTP(s) over TCP isn't the best for video due to the way TCP-congestion management works), but there is nothing stopping you from writing a client-side reconnect.

**Comment by rolandjitsu** [comment]
I was afraid that we might need to do that. I guess streaming over UDP is probably a better idea. I guess I will use a pistache endpoint to start the streaming and get the port it's running on and another endpoint to stop it.

Thanks for the help 👍
