### ISSUE TITLE
C++03 support

### ISSUE THREAD

**Issue by jeritiana** [oktal/pistache#69]
Hi,
The library seems very powerful. I was just wondering why the use of C++11?
Do you think it would it be a huge effort to support C++03?
And why not compiling my app with a C++11 compiler: because of industrial maintainability, standard dev toolsets shipped with Centos 6 for example.
Thanks!

**Comment by oktal** [comment]
Hello,

> The library seems very powerful. I was just wondering why the use of C++11?

Because it uses a lot of features of C++11, like `variadic templates`, `lambdas`, `for-range based-loops` as well as standard library components like `unordered_map`, `shared_ptr`, ...

> Do you think it would it be a huge effort to support C++03?

Yes, and it would be unfortunately nearly impossible, and I don't plan on supporting non-C++11 compliant compilers.

If you can not use a C++11 compiler, you are out of luck with this library
