### ISSUE TITLE
make fails after updating to Debian 9 Stretch

### ISSUE THREAD

**Issue by janhkrueger** [oktal/pistache#93]
Hello,

just updated to Debian 9.
Unfortunately, the step "Linking CXX executable run_async_test" fails during make.

Do I miss something?

g++ (Debian 6.3.0-18) 6.3.0 20170516
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux

[compile.log.txt](https://github.com/oktal/pistache/files/1086423/compile.log.txt)

Because the format of the log is very ugly after uploading here, I added the log to a gist:
https://gist.github.com/janhkrueger/d104d5672850462ed8bbe1de3bb3d0d3

**Comment by jeffvandyke** [comment]
I just ran a build on a fresh VirtualBox installation of Debian 8 with Gnome, same g++ version, same Linux kernel version, same Debian version, same everything that I can tell you've given, and I followed the instructions on <http://pistache.io/quickstart>, and it worked without complaint; I was unable to reproduce this problem. You sure you followed all the steps on that Getting Started page? You could try a fresh clone in a new directory, but the quick test with your specs seemed to work for me. Let me know if a fresh clone works.

**Comment by janhkrueger** [comment]
Before the upgrade to Stretch I used Debian 8 on the same machine and it worked so I think I followed the quickstart instructions correct.
After the failed build I did a fresh clone without any improvements.
Could there other dependencies which changed in Stretch?

**Comment by jeffvandyke** [comment]
None that seem obvious from the release notes. Because a fresh installation of Debian 9 worked without a hitch, I think there's something perhaps related to libraries on your machine that's failing that one step. Unfortunately I'm not that good at diagnostics on build environments, except to say to start as clean as possible. Perhaps someone else would know better. In the meantime, at least you are still building your main targets, both `libnet_static.a` and `libnet.so`, so that should be good for developing with. Sorry I couldn't help more.

**Comment by janhkrueger** [comment]
Oh, nothing to be sorry about. Pistache is a great framework and your comments are always a good source of help.

I will test it at the weekend with a fresh installation of Stretch and report back.

**Comment by janhkrueger** [comment]
Whatever happend during dist-upgrade.
On a fresh install all works again like it has previously.

Whatever has gone wrong during dist-upgrade, I'm not able to reproduce it even on a snapshot of the server.
I'm closing the issue.
